services:
  - type: web
    name: mcmcare-chatbot
    runtime: python
    rootDir: chatbot
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn as_chatbot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SPRING_API_URL
        value: https://mcm-api.likepigs.shop
  - type: web
    name: mcmcare-ai
    runtime: python
    rootDir: ai-model/03_api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
